import React from "react";
import Head from "next/head";
import Footer from "../../common/Footer";
import Topbar from "../../common/Topbar";
import LayoutHeader from "./LayoutHeader";

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>
          Corelaw- Law firm, Lawyers & Legal Service React NextJs Template
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icons/fr-logo.png" />
      </Head>
      <Topbar />
      <LayoutHeader />
      {children}
      <Footer />
    </>
  );
}

export default Layout;
