import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Footer from '../common/Footer'
import Preloader from '../common/Preloader'
import About from '../components/about/About'
import Banner from '../components/banner/Banner'
import Contact from '../components/contact/Contact'
import Header from '../components/header/Header'
import Practice from '../components/practice/Practice'
import Scheduler from "../components/scheduler/Scheduler";

function Index() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 3000);
  }, []);
  return (
      <>
        {loading ? (
            <Preloader style="home2preloader" />
        ) : (
            <>
              <Head>
                <title>FABIA ROJAS - ABOGADA</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="assets/images/icons/fr-logo-transparent.png" />
              </Head>
              <Header/>
              <Banner/>
              <Practice/>
              <About/>
              <Scheduler/>
              {/*<History4/>
              <CaseStidy4/>
              <Attrony4/>*/}
              <Contact/>
              {/*<Testimonial4/>
               <Blog4/>*/}
              <Footer/>
            </>
        )}
      </>
  )
}

export default Index
