import React, { useEffect, useState } from "react";
import Head from "next/head";
import Footer from "../common/Footer";
import Preloader from "../common/Preloader";
import About3 from "../components/about/About3";
import Attrony3 from "../components/Attrony/Attrony3";
import Banner3 from "../components/banner/Banner3";
import Blog3 from "../components/blog/Blog3";
import CaseStudy3 from "../components/caseStudy/CaseStudy3";
import Contact3 from "../components/contact/Contact3";
import Header3 from "../components/header/Header3";
import History3 from "../components/home3/History3";
import Practice3 from "../components/practice/Practice3";
import Testimonial3 from "../components/testimonial/Testimonial3";

function Home3() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 3000);
  }, []);
  return (
   
        <div className="dark-mode-bg">
        {loading ? (
          <Preloader style="home2preloader" />
        ) : (
          <>
            <Head>
        <title>Corelaw- Law firm, Lawyers & Legal Service React NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icons/logo-icon.svg" />
      </Head>
           <Header3 />
          <Banner3 />
          <Practice3 />
          <About3 />
          <History3/>
          <CaseStudy3/>
          <Attrony3/>
          <Contact3/>
          <Testimonial3/>
          <Blog3/>
          <Footer/>
          </>
        )}
      </div>
  
  );
}

export default Home3;
