import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Footer from '../common/Footer'
import Preloader from '../common/Preloader'
import About4 from '../components/about/About4'
import Attrony4 from '../components/Attrony/Attrony4'
import Banner4 from '../components/banner/Banner4'
import Blog4 from '../components/blog/Blog4'
import CaseStidy4 from '../components/caseStudy/CaseStidy4'
import Contact3 from '../components/contact/Contact3'
// import Banner3 from '../components/banner/Banner3'
import Header4 from '../components/header/Header4'
import History4 from '../components/home4/History4'
import Practice4 from '../components/practice/Practice4'
import Testimonial4 from '../components/testimonial/Testimonial4'

function Index4() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 3000);
  }, []);
  return (
  
      <>
      {loading ? (
        <Preloader style="home2preloader" />
      ) : (
        <>
        <Head>
        <title>Corelaw- Law firm, Lawyers & Legal Service React NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icons/logo-icon.svg" />
      </Head>
       <Header4/>
     <Banner4/>
     <Practice4/>
     <About4/>
     <History4/>
     <CaseStidy4/>
     <Attrony4/>
     <Contact3/>
     <Testimonial4/>
     <Blog4/>
     <Footer/>
        </>
      )}
    </>
  )
}

export default Index4